// <auto-generated />
using System;
using GoodBadHabitsTracker.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodBadHabitsTracker.Infrastructure.Migrations
{
    [DbContext(typeof(HabitsDbContext))]
    partial class HabitsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoodBadHabitsTracker.Core.Domain.Habit", b =>
                {
                    b.Property<Guid>("HabitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsGoalInTime")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGood")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRepeatDaily")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("Quantity")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("ReminderTime")
                        .HasColumnType("time");

                    b.Property<byte[]>("RepeatDaysOfMonth")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RepeatDaysOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HabitId");

                    b.ToTable("Habits", (string)null);

                    b.HasData(
                        new
                        {
                            HabitId = new Guid("6ecb8c16-d048-4e9b-8d30-26792bf54de4"),
                            Frequency = "daily",
                            IsGoalInTime = true,
                            IsGood = true,
                            Name = "TestHabit",
                            Quantity = (byte)1,
                            ReminderTime = new TimeOnly(12, 0, 0),
                            RepeatDaysOfWeek = "[\"monday\",\"saturday\"]",
                            StartDate = new DateOnly(2023, 11, 25),
                            UserId = new Guid("62907db2-763d-4fcf-98fa-d8f0da76d00b")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
